<!-- This PHP file is reached when a user clicks on a link received when is password
is lost!-->

<?php
session_start(); 
//VARIABLES
$tbl_name="Reset";

//DB connection information
require "db_connect.php";

//This confirmation code is generated by the link given to the user
$confirmation=$_GET['passkey'];

//Confirmation code retrieval from DB
$sql="SELECT * FROM $tbl_name WHERE confirmation ='$confirmation'";
$result=mysql_query($sql);

if($result){

	// Count how many rows have this passkey
	$count=mysql_num_rows($result);
	
	if($count==1){
		$rows=mysql_fetch_array($result1);
		$email=$rows['email'];
		$_SESSION['email'] = $email;
		header('Location:/password_change.php');
	}
	//If there is less or more than one count, user is redirected
	//to "Wrong Confirmation Code" Page
	else{
		header('Location:/wcc.php');
	}

}

?>